version: "3.8"
services:
  surreal:
    image: surrealdb/surrealdb
    ports:
      - "8000:8000"
    volumes:
      - ./db_data/content:/data/
    environment:
      - SURREAL_NAMESPACE=default
    command:
      [
        "start",
        "--username",
        "recipe_robot",
        "--password",
        "muchsecret",
        "--strict",
        "file:/data/database",
      ]
