FROM surrealdb/surrealdb as old

FROM clux/muslrust:stable as build

COPY --from=old /surreal /surreal

RUN mkdir /data
RUN addgroup -gid 1000 appgroup && adduser --uid 1000 --ingroup appgroup --disabled-password appuser
RUN chown -R appuser:appgroup /surreal /data

RUN chmod -R 777 /data
RUN chmod -R 777 /surreal

USER 1000 

ENTRYPOINT ["/surreal"]
