FROM rust:latest as builder

WORKDIR /usr/src/recipe_ranger

# install system dependencies

RUN apt update
RUN apt install -y musl-tools

# build

RUN rustup target add x86_64-unknown-linux-musl
# RUN rustup target add aarch64-unknown-linux-musl
COPY src ./src
COPY Cargo.toml .
COPY Cargo.lock .

RUN cargo install --target x86_64-unknown-linux-musl --path .
# RUN cargo install --target aarch64-unknown-linux-musl --path .

# use multi-stage build to reduce image size

FROM alpine:latest
COPY --from=builder /usr/local/cargo/bin/recipe_ranger .
COPY db_data/setup db_data/setup
COPY .surrealdb /.surrealdb
ENTRYPOINT ["./recipe_ranger"]

