FROM node:20-buster-slim as build
COPY . .
RUN npm i -g bun
RUN bun i
RUN bun run build

RUN ls -r /dist/img 

FROM nginx:1.27
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=build /dist/ /var/www/
